theme: jekyll-theme-minimal
name: "Saboia da Silva, Maíra"
title: "Maíra Saboia, PhD."



cv: https://mairasaboia.github.io/CV.pdf
linkedin: https://www.linkedin.com/in/ma%C3%ADra-saboia-2492ba13
googlescholar: https://scholar.google.com/citations?user=ED0FQloAAAAJ&hl=en
show_downloads: true

# googlescholar    : "http://yourfullgooglescholarurl.com"
# <link rel="canonical" href="http://www.pas.rochester.edu/~hbarbosa/">
# <meta property="og:url" content="http://www.pas.rochester.edu/~hbarbosa/">

# email: mairasab@buffalo.edu
# [Curriculum Vitae](CV.pdf)
# Short bio or description (displayed in the header)
description: Postdoc at NASA JPL
logo: profilepic.jpg
# logo: beaver-robot-hi.jpg
# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/avatar-icon.png"
# url-pretty: "mairasaboia.com"
# [googlescholar](https://scholar.google.com/citations?user=ED0FQloAAAAJ&hl=en # anything in your profile username that comes after plus.google.com/)

pages_list:
  Research: '/research/research'
  Publications: '/publications/publications'
  News: '/news/news'
  Talks: '/talks/talks'
  Ta: '/ta/ta'
  Resources: '/resources/resources'
#   Current: 'current/current'
  
# # # Site Author
# # author:
# #   name             : "Your Sidebar Name"
# #   avatar           : #"profile.png"
# #   bio              : #"Your biography for the left-hand sidebar"
# #   location         : "Location"
# #   employer         :
# #   googlescholar    : "http://yourfullgooglescholarurl.com"
# #   email            :
# #   researchgate     :  # example: "https://www.researchgate.net/profile/yourprofile"
# #   uri              :
# #   bitbucket        :
# #   codepen          :
# #   dribbble         :
# #   flickr           :
# #   facebook         :
# #   foursquare       :
# #   github           : #"academicpages"
# #   google_plus      :
# #   keybase          :
# #   instagram        :
# #   lastfm           :
# #   linkedin         :
# #   orcid            : #"http://orcid.org/yourorcidurl"
# #   pinterest        :
# #   soundcloud       :
# #   stackoverflow    : # http://stackoverflow.com/users/123456/username
# #   steam            :
# #   tumblr           :
# #   twitter          : #"replacethistwitterhandle"
# #   vine             :
# #   weibo            :
# #   xing             :
# #   youtube          :
# #   wikipedia        :
  

# #   Feed: '/atom.xml' that comes after plus.google.com/
