theme: jekyll-theme-minimal
name: "Saboia da Silva, Maíra"
title: "Saboia da Silva, Maíra"
<link rel="canonical" href="http://www.pas.rochester.edu/~hbarbosa/">
<meta property="og:url" content="http://www.pas.rochester.edu/~hbarbosa/">


# [Curriculum Vitae](CV.pdf)
# Short bio or description (displayed in the header)
description: PhD Candidate, Computer Science and Engineering, University at Buffalo
logo: profilepic.jpg
# logo: beaver-robot-hi.jpg
# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/avatar-icon.png"
# url-pretty: "mairasaboia.com"
# [googlescholar](https://scholar.google.com/citations?user=ED0FQloAAAAJ&hl=en # anything in your profile username that comes after plus.google.com/)

pages_list:
  Research: '/research/research'
  Publications: '/publications/publications'
  News: '/news/news'
  Spotlight Talks: '/talks/talks'
#   Feed: '/atom.xml' that comes after plus.google.com/
