theme: jekyll-theme-minimal
name: "Saboia da Silva, Maíra"
title: "Saboia da Silva, Maíra"



cv: https://mairasaboia.github.io/CV.pdf
linkedin: https://www.linkedin.com/in/ma%C3%ADra-saboia-2492ba13
googlescholar: https://scholar.google.com/citations?user=ED0FQloAAAAJ&hl=en
show_downloads: true

