theme: jekyll-theme-minimal
title: Maira Saboia
logo: beaver-robot-hi.jpg

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/avatar-icon.png"
url-pretty: "mairasaboia.com"
